from __future__ import annotations

from enum import StrEnum


class Direction(StrEnum):
    BULLISH = "bullish"
    BEARISH = "bearish"


class Timeframe(StrEnum):
    M1 = "M1"
    M15 = "M15"
    H1 = "H1"
    D1 = "D1"


class StrategyMode(StrEnum):
    A_INVALIDATION_S2 = "A_INVALIDATION_S2"
    B_NO_S2_INVALIDATION = "B_NO_S2_INVALIDATION"
    C_S2_INSIDE_S1 = "C_S2_INSIDE_S1"


class PdMode(StrEnum):
    OB_SOLID = "OB_SOLID"
    FVG = "FVG"
    OB_OR_FVG = "OB_OR_FVG"


class SetupEventType(StrEnum):
    H1_SIGNAL = "H1_SIGNAL"
    M15_DOUBLE_SWING_VALIDATED = "M15_DOUBLE_SWING_VALIDATED"
    SETUP_REJECTED_NO_DOUBLE_SWING = "SETUP_REJECTED_NO_DOUBLE_SWING"
    SETUP_INVALIDATED_S2 = "SETUP_INVALIDATED_S2"
    LEG_FOUND = "LEG_FOUND"
    OTE_CREATED = "OTE_CREATED"
    OB_SELECTED = "OB_SELECTED"
    FVG_SELECTED = "FVG_SELECTED"
    PD_TOUCHED = "PD_TOUCHED"
    REJECTION_CONFIRMED = "REJECTION_CONFIRMED"
    RISK_REJECTED = "RISK_REJECTED"
    ORDER_CREATED = "ORDER_CREATED"
    TRADE_OPENED = "TRADE_OPENED"
    TRADE_CLOSED_TP = "TRADE_CLOSED_TP"
    TRADE_CLOSED_SL = "TRADE_CLOSED_SL"
    TRADE_CLOSED_AMBIGUOUS = "TRADE_CLOSED_AMBIGUOUS"
